Document Policy demos
GoogleChromeLabs/feature-policy-demos pull request #27
Opened 2020-07-20 17:57 UTC by huchenlei

## Echo request query as policy headers
Previously the site uses `iframe.allow` to change feature policy value for demo purposes. However, document policy cannot be set with iframe attribute. The only option is 'Document-Policy' HTTP header.

This PR abandons the allow attribute approach, and uses HTTP header to set policy for both feature policy and document policy.

## Add policy value selector for non-boolean policy values
Previously, we can only select ON or OFF as policy value state from top right links, which is not particular suitable for policies with non-boolean values, such as image policies.

This PR provides the flexiblity to add custom policy value selection.

## Refresh image policy demos
As image policies are migrated to document policy, old demos are broken. This PR refreshes the corresponding headers
so that the demos are back to a functional state.

2020-07-22 16:09 UTC, jpchase commented on public/js/policies.json
> +    "off": "Document-Policy: unsized-media",
I think the repetition of the header in every policy can be avoided. You could add a key to each policy to indicate if it's Permission Policy vs Document Policy, and then construct the header (if needed) in the code that parses the json.

For example:

```
[{
  "id": "unsized-media",
  "name": "Unsized Media",
  "type": "images",
  "framework": "permissions" // or "document"
``` 

There's probably a better name than "framework", but "type" was already used.

2020-07-22 16:16 UTC, jpchase commented on public/js/app.js
> +        <a href="${p.url}?${headerParam}" class="policy-name" onclick="updatePage(this, '${p.id}')">
With Document Policy supporting values, I realize that it's no longer sufficient to hard-code "on". However, I don't think it's necessary (or a good idea) to encode the entire header into the url.  Maybe this could just use the key names from the |usage| section for each policy. The loading/update can load the policy values from the json, rather than trusting whatever is provided in the url.  The urls for "on" shouldn't even need to change for Permission Policy.

2020-07-22 16:19 UTC, jpchase commented on public/js/shared.js
> +    policy.usage = Object.entries(policy.usage)
As in other comments, I think this complicated mapping could be avoided, by not encoding the full policy in the url.

2020-07-22 16:22 UTC, jpchase commented on public/js/shared.js
> +      ${unsafeHTML(policyValueSelector(policy))}
The use of |unsafeHTML| is a good indicator that encoding the full policy into the url is something to be avoided.

2020-07-22 18:18 UTC, huchenlei commented on public/js/shared.js
> +      ${unsafeHTML(policyValueSelector(policy))}
The use of |unsafeHTML| is a problem with lit-html library, not the encoding of full policy.

If not wrapped by |unsafeHTML|, the whole content would be treat as a plain text node.

2020-07-22 20:04 UTC, huchenlei commented on public/js/policies.json
> +    "off": "Document-Policy: unsized-media",
Add enum field `policyType`.

2020-07-22 20:04 UTC, huchenlei commented on public/js/app.js
> +        <a href="${p.url}?${headerParam}" class="policy-name" onclick="updatePage(this, '${p.id}')">
Done.

2020-07-22 20:04 UTC, huchenlei commented on public/js/shared.js
> +    policy.usage = Object.entries(policy.usage)
Removed.

2020-07-22 20:08 UTC, huchenlei commented
The most recent patch made following improvements: 

- pick policy value from policies.json on server side 
- passes usage key as request param instead of the whole header

2020-10-14 14:58 UTC, huchenlei commented
Hi Jason,

Gentle ping on the review of this PR.

2020-10-14 21:12 UTC, jpchase requested changes
(I can't seem to comment on unchanged lines) The demo pages for the image policies (oversized, unoptimized, unsized), all seem to reference buttons by name, e.g. "Click the disallow/allow buttons above". That text should probably be updated, now that the buttons will have different values, instead of "on"/"off".

Also, it would be helpful if you could provide a screenshot of one of the updated pages. It's hard to evaluate the end result from just looking at the code changes.

2020-10-15 14:49 UTC, huchenlei commented on public/js/shared.js
> +  return `
Initially I tried using html tag, but it does not work as expected.

As `unsafeHTML` is used in following lines of the template prior to my PR:

```html
<ul class="details-info">
      <li><label>What</label><span>${unsafeHTML(policy.what)}</span></li>
      <li><label>Why</label><span>${unsafeHTML(policy.why)}</span></li>
      <li><label>Examples</label><div>${unsafeHTML(examples)}</div></li>
</ul>
```

I believe it is the correct move to use `unsafeHTML` here as well.

2020-10-15 14:58 UTC, huchenlei commented on public/js/shared.js
> +  return `
Went to the implementation of `html` tag in lithtml and realized that it was not the `querySelector` level template causing the problem. Suggestion accepted.

2020-10-15 15:16 UTC, huchenlei commented on public/js/shared.js
> +        return `<a href="${policy.url}?${policyValue}" class="try-button" ${active}
Comment accepted by replacing

```javascript
  return html `
    <span class="trylinks">
      ${desc}
      ${unsafeHTML(optionButtons.join('\n'))}
    </span>
  `;
```

with 

```javascript
  return html `
    <span class="trylinks">
      ${desc}
      ${repeat(optionButtons, i => i)}
    </span>
  `;
```

2020-10-15 15:18 UTC, huchenlei commented on public/js/shared.js
> +        return `<a href="${policy.url}?${policyValue}" class="try-button" ${active}
Done.

2020-10-15 15:21 UTC, huchenlei commented on public/js/shared.js
> +      ${optionButtons.join('\n')}
`.join('\n')` removed, because lithtml joins template together when array of template is passed as template argument.

2020-10-15 15:25 UTC, huchenlei commented on public/js/policies.json
> +    "on": "unsized-media=?0"
I think the original intension is:

- off: default behaviour
- on: overriden behaviour

Are we planning to change this?
Note: `unsized-media 'none'` has the same behaviour as `unsized-media=?0`.

2020-10-15 16:05 UTC, huchenlei commented
![Screen Shot 2020-10-15 at 12 01 58 PM](https://user-images.githubusercontent.com/20929282/96155707-3df61c80-0ede-11eb-8f0d-b583287cc8c6.png)

Note: For document policy, the error banner of policy not support will be replace with a warning banner because there is no document policy js api to tell whether the policy is supported or not. For similar reason, the bluebox showing `Page Disables XXX` will also be removed for document policy pages. These will be done in a follow-up PR.

2020-10-19 14:53 UTC, huchenlei commented
Hi Jason,

Gentle ping on the review of this PR.

2020-10-23 14:53 UTC, jpchase commented on public/demos/oversized-images.html
> +  Images that have image_size / container_size ratio exceed given threshold should
Nit: When I see |image_size| and |container_size| they sound like properties that should exist on an element or API somewhere. I don't think that's the case, so I'd suggest using a less technical explanation.

```suggestion
  Images where the ratio of intrinsic dimensions to container size exceeds the given threshold should
```

2020-10-23 15:05 UTC, jpchase commented on public/js/shared.js
> +            class="try-button" onclick=updatePolicyValue(this) active
I think you should be able to use [ifDefined](https://lit-html.polymer-project.org/guide/template-reference#ifdefined) to avoid having the repetitive if/else branches.

Something like this, although you may need to experiment with the best "defined" value:

```suggestion
            class="try-button" onclick=updatePolicyValue(this) active="${ifDefined(policyValue.localeCompare(currentPolicyValue) === 0 ? true : undefined)}"
```

2020-10-23 15:05 UTC, jpchase commented on public/js/policies.json
> +    "on": "unsized-media=?0"
Right, that's a good point for the intention behind off/on. I was mapping that more literally to true/false values, and forgetting the inversion (i.e. off = unsized allowed). The config makes sense as you have it.

2020-10-23 17:40 UTC, huchenlei commented on public/demos/oversized-images.html
> +  Images that have image_size / container_size ratio exceed given threshold should
Done.

2020-10-23 17:40 UTC, huchenlei commented on public/demos/unoptimized-lossy-images.html
> + Images with bpp(byte per pixel) exceeds the threshold should render as placeholder images.
Done.

2020-10-23 17:40 UTC, huchenlei commented on public/js/shared.js
> +            class="try-button" onclick=updatePolicyValue(this) active
Done.

2020-10-23 17:51 UTC, jpchase approved these changes
LGTM!

2020-10-23 17:51 UTC, merged