Update demos to use Permissions-Policy header syntax
GoogleChromeLabs/feature-policy-demos pull request #30
Opened 2020-10-14 14:56 UTC by huchenlei

This PR renames all remaining 'feature policy' occurence with 'permissions policy' in 
- code comments
- function names, variable names
- html content
- README

Header syntax in policies.json has been updated.

Both the 'Permissions-Policy' HTTP header and 'Feature-Policy' HTTP header will be send for backward compatibility.
(See modification in server.mjs)

2020-10-26 20:58 UTC, jpchase requested changes

2020-10-26 20:58 UTC, jpchase commented on permissions-policy-header.mjs
> +          // Remove leading and tailing '"' in permissions header syntax.
Nit: I think this should be "trailing"
```suggestion
          // Remove leading and trailing '"' in permissions header syntax.
```

2020-10-26 20:58 UTC, jpchase commented on permissions-policy-header.mjs
> +      .map(([policyName, allowlist]) => `${policyName} ${allowlist.join(' ')}`)
Do you need to do the object spreading here (i.e. the `...this.policies.entries()`)? Given that the array is being mapped to create a new array anyways, could the spreading be removed?

```suggestion
return this.policies.entries().map(.....)
```

2020-10-26 20:58 UTC, jpchase commented on permissions-policy-header.mjs
> +        [...this.policies.entries()]
Ditto for not using object spreading.

2020-10-26 20:58 UTC, jpchase commented on permissions-policy-header.mjs
> +      .map(([policyName, allowlist]) => `${policyName}=(${allowlist.join(' ')})`)
Ditto for not using object spreading.

2020-10-26 20:58 UTC, jpchase commented on public/js/app.js
> + * @param {string} id Permissions policy id.
Nit: ditto for applying to both Permissions and Document policy?

2020-10-26 20:58 UTC, jpchase commented on public/js/shared.js
> + * Updates the UI metadata header when a permissions policy is selected.
Nit: ditto for applying to both Permissions and Document policy?

2020-10-26 20:58 UTC, jpchase commented on public/js/shared.js
> +  'policy' in document ||
Ditto for not supporting `document.policy`.

2020-10-26 20:58 UTC, jpchase commented on public/js/shared.js
> +  document.policy ||
Ditto for not supporting `document.policy`.

2020-10-26 20:58 UTC, jpchase commented on public/js/app.js
> +    document.policy || document.permissionsPolicy || document.featurePolicy;
As discussed offline, I think that `document.policy` was only briefly supported (for one release?). It seems fine to not support that here.

2020-10-26 20:58 UTC, jpchase commented on public/demos/animations.html
> +  <title>Permissions Policy: animations example</title>
According to the [Chromium source](https://source.chromium.org/chromium/chromium/src/+/master:out/Debug/gen/third_party/blink/common/feature_policy/document_policy_features.cc;l=70;drc=5c28732f7b15df34c9fe70dae7f03c791c469df5), animations are in Document, not Permissions Policy.

2020-10-26 20:58 UTC, jpchase commented on public/js/policies.json
> +  "policyType": "Permissions-Policy",
Ditto for animations being under Document Policy.

2020-10-26 20:58 UTC, jpchase commented on public/index.html
> +  <title>Permissions Policy Kitchen Sink</title>
There's demo pages for both Permissions and Document Policy, so that should clearer.

2020-10-27 14:17 UTC, huchenlei commented on README.md
> +## Permissions Policy Demos
Done.

2020-10-27 14:17 UTC, huchenlei commented on README.md
> +Kitchen sink of [permissions policy](https://www.chromestatus.com/feature/5745992911552512) demos.
Done.

2020-10-27 14:17 UTC, huchenlei commented on public/demos/autoplay.html
> +<p>The video below uses <code>autoplay</code> attribute. Reload the page with the permissions policy on/off to see the effect on it auto playing.</p>
Done.

2020-10-27 14:18 UTC, huchenlei commented on public/js/app.js
> + * @return {!Object} Permissions policy info.
Done.

2020-10-27 14:19 UTC, huchenlei commented on server.mjs
> +import {FeaturePolicyHeader, PermissionsPolicyHeader} from './permissions-policy-header.mjs';
Done.

2020-10-27 14:19 UTC, huchenlei commented on public/js/shared.js
> +  document.policy ||
Done.

2020-10-27 14:20 UTC, huchenlei commented on public/js/app.js
> +    document.policy || document.permissionsPolicy || document.featurePolicy;
Done.

2020-10-27 14:21 UTC, huchenlei commented on public/demos/animations.html
> +  <title>Permissions Policy: animations example</title>
Done.

2020-10-27 14:25 UTC, huchenlei commented on public/js/policies.json
> +  "policyType": "Permissions-Policy",
Done.

2020-10-27 14:26 UTC, huchenlei commented on public/index.html
> +  <title>Permissions Policy Kitchen Sink</title>
Done.

2020-10-28 17:10 UTC, huchenlei commented on permissions-policy-header.mjs
> +          // Remove leading and tailing '"' in permissions header syntax.
Done.

2020-10-28 17:11 UTC, huchenlei commented on permissions-policy-header.mjs
> +      .map(([policyName, allowlist]) => `${policyName} ${allowlist.join(' ')}`)
`Map.entires()` returns Iterator object, which does not have `map` method. The spread here is necessary to convert Iterator to Array.

2020-10-28 17:11 UTC, huchenlei commented on public/js/app.js
> + * @param {string} id Permissions policy id.
Done.

2020-10-28 17:12 UTC, huchenlei commented on public/js/shared.js
> + * Updates the UI metadata header when a permissions policy is selected.
Done.

2020-10-28 17:31 UTC, jpchase approved these changes
LGTM

2020-10-28 17:31 UTC, jpchase commented on permissions-policy-header.mjs
> +      .map(([policyName, allowlist]) => `${policyName} ${allowlist.join(' ')}`)
Ah, I get it. I haven't used Map much, but a quick search suggests using the spread is most common way to handle this case.

2020-10-28 17:38 UTC, merged