Update document policy feature demo page banner
GoogleChromeLabs/feature-policy-demos pull request #31
Opened 2020-10-15 18:22 UTC by huchenlei

Currently there is no way to tell wether document policy is supported in the browser, because there is no JS API for document policy. 

- Use a warning banner instead of error banner for document policy demo pages.
- Remove blue `feature-allowed-banner`.

Before: 
![Screen Shot 2020-10-15 at 2 21 55 PM](https://user-images.githubusercontent.com/20929282/96170598-cc27ce00-0ef1-11eb-9268-bfadf6d8e21d.png)

After:
![Screen Shot 2020-10-15 at 2 20 45 PM](https://user-images.githubusercontent.com/20929282/96170623-d1851880-0ef1-11eb-9a3d-56a064e6b7eb.png)

2020-10-26 19:16 UTC, jpchase requested changes

2020-10-26 19:16 UTC, jpchase commented on public/js/shared.js
>    }
Some of the Document Policy demo pages have intentionally removed the banner. I'd suggest deleting the `console.warn` on line 185, since it will end up spamming the console for those pages.

2020-10-26 19:16 UTC, jpchase commented on public/js/shared.js
> +    return `
Return as html, e.g.:
```suggestion
    return html`
```

2020-10-26 19:16 UTC, jpchase commented on public/js/shared.js
> +    return `
Ditto for return as html.

2020-10-26 19:16 UTC, jpchase commented on public/js/shared.js
> +    ${unsafeHTML(notSupportedBanner(policy))}`;
You should be able to remove the `unsafeHTML`, if earlier comments are addressed to have `notSupportedBanner()` return html.

2020-10-27 14:10 UTC, huchenlei commented on public/js/shared.js
> +    return `
Done.

2020-10-27 14:10 UTC, huchenlei commented on public/js/shared.js
> +    ${unsafeHTML(notSupportedBanner(policy))}`;
Done.

2020-10-27 14:11 UTC, huchenlei commented on public/js/shared.js
>    }
Done.

2020-10-27 14:13 UTC, huchenlei commented on public/js/shared.js
> +    return `
Done.

2020-10-28 16:48 UTC, jpchase approved these changes
LGTM

2020-10-28 16:49 UTC, merged